---
- name: Local Install of Tools
  hosts: localhost
  gather_facts: true
  connection: local
  become: true
  vars_files:
    - vault.yml
    - vars.yml
  tasks:

    - name: Import nvm.yml
      ansible.builtin.import_tasks: playbooks/nvm.yml
      tags: nvm

    - name: Import docker.yml
      ansible.builtin.import_tasks: playbooks/docker.yml
      tags: docker

    - name: Import chrome.yml
      ansible.builtin.import_tasks: playbooks/chrome.yml
      tags: chrome

    - name: Import neovim.yml
      ansible.builtin.import_tasks: playbooks/neovim.yml
      tags:
        - neovim
        - nvim

    - name: Import helix-editor-ubuntu.yml
      ansible.builtin.import_tasks: playbooks/helix-editor-ubuntu.yml
      tags: helix

    - name: Import lazygit.yml
      ansible.builtin.import_tasks: playbooks/lazygit.yml
      tags: lazygit
