---
- name: Local Install of Tools
  hosts: localhost
  gather_facts: true
  connection: local
  become: true
  vars_files:
    - vault.yml
  vars:
    - show_debug: false
    - neovim_appimage_url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    - lazygit_release_url: "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"
    - lazygit_download_prefix: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_"
    - lazygit_download_suffix: '_Linux_x86_64.tar.gz'

  tasks:
    - name: Import neovim.yml
      ansible.builtin.import_tasks: playbooks/neovim.yml

    - name: Import helix-editor-ubuntu.yml
      ansible.builtin.import_tasks: playbooks/helix-editor-ubuntu.yml

    - name: Import lazygit.yml
      ansible.builtin.import_tasks: playbooks/lazygit.yml
