---
- name: Install Helix Editor
  tags: helix
  block:
    - name: Add Helix Editor repository
      ansible.builtin.apt_repository:
        repo: "ppa:maveonair/helix-editor"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Helix Editor
      ansible.builtin.apt:
        name: helix
        state: present
